{ config, ... }:

let
  homeDir = config.home.homeDirectory;
in
{
  # Disable default SSH agent (Bitwarden handles it)
  services.ssh-agent.enable = false;

  programs.fish = {
    enable = true;

    # Session-wide env
    shellInit = ''
      set -gx SSH_AUTH_SOCK "${homeDir}/.bitwarden-ssh-agent.sock"
    '';

    # Interactive-only: greeting + theme + prompt
    interactiveShellInit = ''
      # ---- fish_greeting ----
      function fish_greeting
          set -l trans_blue (set_color 55cdfc)
          set -l trans_pink (set_color f7a8b8)
          set -l trans_white (set_color ffffff)
          set -l reset (set_color normal)

          set -l lines \
              "Nya~~ Nya~~" \
              "MørStãr here~~" \
              "I am DEFINITELY NOT femboy btw" \
              "Coding, Gaming, dressing up today~~" \
              "Still Cis Tho"

          set -l colors \
              $trans_blue \
              $trans_pink \
              $trans_white \
              $trans_pink \
              $trans_blue

          set -l cols (tput cols 2>/dev/null; or echo 80)

          for i in (seq (count $lines))
              set -l text $lines[$i]
              set -l color $colors[$i]
              set -l visible_len (string length -- $text)
              set -l pad (math "floor(($cols - $visible_len) / 2)")

              if test $pad -gt 0
                  echo -n (string repeat -n $pad ' ')
              end
              echo $color$text$reset
          end
      end

      # ---- frozen theme (generated by fish_config) ----
      set --global fish_color_autosuggestion 707A8C
      set --global fish_color_cancel --reverse
      set --global fish_color_command 5CCFE6
      set --global fish_color_comment 5C6773
      set --global fish_color_cwd 73D0FF
      set --global fish_color_cwd_root red
      set --global fish_color_end F29E74
      set --global fish_color_error FF3333
      set --global fish_color_escape 95E6CB
      set --global fish_color_history_current --bold
      set --global fish_color_host --reset
      set --global fish_color_host_remote yellow
      set --global fish_color_normal CBCCC6
      set --global fish_color_operator FFCC66
      set --global fish_color_param CBCCC6
      set --global fish_color_quote BAE67E
      set --global fish_color_redirection D4BFFF
      set --global fish_color_search_match --bold --background=FFCC66
      set --global fish_color_selection --bold --background=FFCC66
      set --global fish_color_status red
      set --global fish_color_user brgreen
      set --global fish_color_valid_path --underline=single
      set --global fish_pager_color_completion --reset
      set --global fish_pager_color_description B3A06D
      set --global fish_pager_color_prefix --bold --underline=single
      set --global fish_pager_color_progress brwhite --bold --background=cyan
      set --global fish_pager_color_selected_background --background=FFCC66
      set --global fish_pager_color_selected_completion
      set --global fish_pager_color_selected_description
      set --global fish_pager_color_selected_prefix
    '';

    # Custom prompt with git integration
    functions.fish_prompt = ''
      set -l laststatus $status

      set -l git_info
      if git rev-parse 2>/dev/null
          set -l git_branch (
              command git symbolic-ref HEAD 2>/dev/null | string replace 'refs/heads/' '''
              or command git describe HEAD 2>/dev/null
              or echo unknown
          )
          set git_branch (set_color -o blue)"$git_branch"
          set -l git_status
          if git rev-parse --quiet --verify HEAD >/dev/null
              and not command git diff-index --quiet HEAD --

              for i in (git status --porcelain | string sub -l 2 | sort | uniq)
                  switch $i
                      case "."
                          set git_status "$git_status"(set_color green)✚
                      case " D"
                          set git_status "$git_status"(set_color red)✖
                      case "*M*"
                          set git_status "$git_status"(set_color green)✱
                      case "*R*"
                          set git_status "$git_status"(set_color purple)➜
                      case "*U*"
                          set git_status "$git_status"(set_color brown)═
                      case "??"
                          set git_status "$git_status"(set_color red)≠
                  end
              end
          else
              set git_status (set_color green):
          end
          set git_info "(git$git_status$git_branch"(set_color white)")"
      end

      set -q fish_prompt_pwd_dir_length
      or set -lx fish_prompt_pwd_dir_length 0

      set_color -b black
      printf '%s%s%s%s%s%s%s%s%s%s%s%s%s' (set_color -o white) '❰' (set_color green) $USER (set_color white) '❙' (set_color yellow) (prompt_pwd) (set_color white) $git_info (set_color white) '❱' (set_color white)
      if test $laststatus -eq 0
          printf "%s✔%s≻%s " (set_color -o green) (set_color white) (set_color --reset)
      else
          printf "%s✘%s≻%s " (set_color -o red) (set_color white) (set_color --reset)
      end
    '';
  };
}
